// Export helpers: JSON, CSV, and a printable HTML report (PDF via browser print).

export function toJSON(records) {
  return JSON.stringify(records, null, 2);
}

export function toCSV(records) {
  const cols = ['ts', 'level', 'logger', 'thread', 'context', 'file', 'lineNo', 'message'];
  const esc = v => {
    if (v == null) return '';
    const s = String(v).replace(/\r?\n/g, ' ');
    return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
  };
  const lines = [cols.join(',')];
  for (const r of records) lines.push(cols.map(c => esc(r[c])).join(','));
  return lines.join('\n');
}

export function toReportHTML(report) {
  const fmt = (n) => (n == null ? '-' : new Date(n).toISOString());
  const levelRows = Object.entries(report.summary.byLevel || {})
    .sort((a, b) => b[1] - a[1])
    .map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
  const fileRows = (report.files || [])
    .map(f => `<tr><td>${f.name}</td><td>${f.size}</td><td>${JSON.stringify(f.levels)}</td></tr>`).join('');
  const errorRows = (report.summary.topErrors || []).slice(0, 25)
    .map(e => `<tr><td>${e.count}</td><td>${e.level}</td><td><code>${escapeHtml(e.sample)}</code></td></tr>`).join('');
  const hintRows = (report.rootCauseHints || [])
    .map(h => `<li>${escapeHtml(h.hint)}</li>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>Log Investigation Report</title>
<style>body{font:14px/1.5 -apple-system,Segoe UI,sans-serif;max-width:1100px;margin:32px auto;padding:0 24px;color:#1a1a1a}
h1,h2{margin-top:32px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top}
th{background:#f6f6f6}code{font-family:ui-monospace,Consolas,monospace;font-size:12px;white-space:pre-wrap}
.kv{display:grid;grid-template-columns:200px 1fr;gap:8px}</style></head><body>
<h1>Log Investigation Report</h1>
<div class="kv"><div>Source</div><div>${escapeHtml(report.root || '')}</div>
<div>Files scanned</div><div>${report.fileCount || 0}</div>
<div>Records parsed</div><div>${report.recordCount || 0}</div>
<div>Time range</div><div>${fmt(report.summary.timeRange?.min)} → ${fmt(report.summary.timeRange?.max)}</div></div>
<h2>Levels</h2><table><tr><th>Level</th><th>Count</th></tr>${levelRows}</table>
<h2>Files</h2><table><tr><th>File</th><th>Size</th><th>Levels</th></tr>${fileRows}</table>
<h2>Top Errors</h2><table><tr><th>Count</th><th>Level</th><th>Sample</th></tr>${errorRows}</table>
<h2>Root cause hints</h2><ul>${hintRows || '<li>No hints generated.</li>'}</ul>
<p style="color:#888;margin-top:48px">Generated by Logalizer · ${new Date().toISOString()}</p>
</body></html>`;
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
